# Generated by Django 4.0.4 on 2022-05-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gpa', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('level', models.IntegerField()),
                ('department', models.CharField(choices=[('general', 'general'), ('cs', 'cs'), ('is', 'is'), ('ds', 'ds'), ('it', 'it'), ('ai', 'ai')], default='general', max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('birth', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=25)),
                ('image', models.ImageField(upload_to='Photos/')),
            ],
        ),
    ]
