# Generated by Django 4.0.4 on 2022-05-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
