# Generated by Django 4.0.4 on 2022-05-17 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_birth_remove_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth',
            field=models.DateField(default=datetime.datetime(2022, 5, 17, 23, 23, 18, 583894, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='Photos/'),
        ),
    ]
