# Generated by Django 4.0.4 on 2022-05-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_impdates_staff_alter_student_birth_alter_student_gpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='impdates',
            name='msg',
            field=models.CharField(max_length=200),
        ),
    ]
