# Generated by Django 4.0.4 on 2022-05-22 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_news_alter_impdates_msg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='impDates',
            new_name='impDate',
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
