# Generated by Django 4.0.4 on 2022-05-22 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_impdates_impdate_rename_news_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impdate',
            old_name='msg',
            new_name='event',
        ),
    ]
