# Generated by Django 4.0.4 on 2022-05-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_msg_impdate_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
